version: '3.0'
services:
  es1:
    container_name: elasticsearch
    build: ./vue-storefront-api/docker/elasticsearch/
    volumes:
      - ./vue-storefront-api/docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./vue-storefront-api/docker/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"

  kibana:
    build: ./vue-storefront-api/docker/kibana/
    volumes:
      - ./vue-storefront-api/docker/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - '5601:5601'
    depends_on:
      - es1

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'

  vue-api:
    build:
      context: ./vue-storefront-api
      dockerfile: docker/vue-storefront-api/Dockerfile
    depends_on:
      - es1
      - redis
    env_file: ./vue-storefront-api/.env
    environment:
      VS_ENV: dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://es1:9200 || exit  1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    volumes:
      - './vue-storefront-api/config:/var/www/config'
      - './vue-storefront-api/ecosystem.json:/var/www/ecosystem.json'
      - './vue-storefront-api/migrations:/var/www/migrations'
      - './vue-storefront-api/package.json:/var/www/package.json'
      - './vue-storefront-api/babel.config.js:/var/www/babel.config.js'
      - './vue-storefront-api/scripts:/var/www/scripts'
      - './vue-storefront-api/src:/var/www/src'
      - './vue-storefront-api/var:/var/www/var'
      - './vue-storefront-api/docker/vue-storefront-api/vue-storefront-api.sh:/usr/local/bin/vue-storefront-api.sh'
    tmpfs:
      - /var/www/dist
    ports:
      - '8080:8080'

  app:
    build:
      context: ./vue-storefront
      dockerfile: docker/vue-storefront/Dockerfile
    env_file: ./vue-storefront/.env
    environment:
      VS_ENV: dev
    volumes:
      - './vue-storefront/babel.config.js:/var/www/babel.config.js'
      - './vue-storefront/config:/var/www/config'
      - './vue-storefront/core:/var/www/core'
      - './vue-storefront/ecosystem.json:/var/www/ecosystem.json'
      - './vue-storefront/.eslintignore:/var/www/.eslintignore'
      - './vue-storefront/.eslintrc.js:/var/www/.eslintrc.js'
      - './vue-storefront/lerna.json:/var/www/lerna.json'
      - './vue-storefront/tsconfig.json:/var/www/tsconfig.json'
      - './vue-storefront/tsconfig-build.json:/var/www/tsconfig-build.json'
      - './vue-storefront/shims.d.ts:/var/www/shims.d.ts'
      - './vue-storefront/package.json:/var/www/package.json'
      - './vue-storefront/src:/var/www/src'
      - './vue-storefront/var:/var/www/var'
    tmpfs:
      - /var/www/dist
    ports:
      - '3000:3000'

volumes:
  esdat1: